# Site settings
title: khusika
email: mail@khusika.com
url: https://khusika.com
description: "Khusika is an android developer from Indonesia"
keywords: "K_TECH, android, khusika, android indonesia, android developer, Khusika Dhamar Gusti, SMAMDA, Universitas Brawijaya, Teknologi Industri Pertanian, Agroindustrial Technology, Raja Brawijaya"
skills: "Android Developer - Graphic Designer"
meta_author: Khusika Dhamar Gusti
address: Sidoarjo, East Java , Indonesia

# Contact form:
# - static : pass through formspree.io to validate email sending
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Khusika

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/khusikadhamar
  - title: instagram
    url: https://instagram.com/khusikadhamargusti
  - title: facebook
    url: https://facebook.com/khusika.dhamar.gusti
  - title: github
    url: https://github.com/khusika
  - title: telegram
    url: https://t.me/khusika

# Build settings
markdown: kramdown
permalink: pretty
